import { StyleSheet } from 'react-native';

export const colors = {
  background: '#F7F8FA', surface: '#FFFFFF', ink: '#183B32', text: '#354D46',
  muted: '#718079', border: '#E7ECE9', green: '#246B53', pale: '#EDF5EF',
  lime: '#DDF1AB', amber: '#9D671F', amberBg: '#FFF5E2', blue: '#487AA0',
};

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  header: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', width: '100%', maxWidth: 720, alignSelf: 'center' },
  brandGroup: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandMark: { width: 38, height: 38, borderRadius: 13, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' },
  brand: { fontSize: 26, fontWeight: '800', color: colors.ink, letterSpacing: -1 },
  brandSub: { fontSize: 9, color: colors.muted, letterSpacing: 1.5, fontWeight: '600' },
  language: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, minHeight: 44, borderRadius: 14, backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border },
  body: { paddingHorizontal: 24, paddingBottom: 24, width: '100%', maxWidth: 720, alignSelf: 'center' },
  title: { fontSize: 30, fontWeight: '700', color: colors.ink, letterSpacing: -.9, lineHeight: 42 },
  subtitle: { fontSize: 14, color: colors.muted, lineHeight: 22, marginTop: 4, marginBottom: 24 },
  eyebrow: { fontSize: 10, letterSpacing: 1.6, fontWeight: '700', color: colors.muted },
  small: { fontSize: 12, color: colors.muted, lineHeight: 19 },
  note: { fontSize: 12, lineHeight: 20, color: colors.muted, marginTop: 10 },
  message: { fontSize: 14, lineHeight: 23, color: colors.text },
  card: { padding: 20, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 22, marginBottom: 16 },
  cardTitle: { fontSize: 16, fontWeight: '700', color: colors.ink, lineHeight: 23 },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  flexible: { flex: 1, minWidth: 0 },
  iconBox: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' },
  badge: { paddingHorizontal: 9, paddingVertical: 5, borderRadius: 8, backgroundColor: colors.pale, alignSelf: 'flex-start' },
  badgeText: { fontSize: 10, color: colors.green, fontWeight: '600' },
  button: { minHeight: 50, backgroundColor: colors.green, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9 },
  buttonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  secondaryButton: { backgroundColor: colors.pale },
  secondaryText: { color: colors.green },
  ghostButton: { backgroundColor: 'transparent', borderWidth: 1, borderColor: colors.border },
  disabled: { opacity: .5 },
  label: { fontSize: 12, fontWeight: '600', color: colors.text, marginBottom: 8 },
  fieldGroup: { marginTop: 16 },
  input: { minHeight: 50, backgroundColor: '#F8FAF8', borderWidth: 1, borderColor: '#E3EAE5', borderRadius: 13, paddingHorizontal: 14, paddingVertical: 13, color: colors.ink, fontSize: 14 },
  focusedInput: { borderColor: colors.green, backgroundColor: '#FFFFFF' },
  sectionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8, marginBottom: 14 },
  section: { fontSize: 17, fontWeight: '700', color: colors.ink },
  link: { color: colors.green, fontSize: 12, fontWeight: '600' },
  textAction: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 5 },
  hero: { backgroundColor: colors.ink, borderRadius: 26, padding: 24, marginBottom: 18, overflow: 'hidden' },
  heroCircle: { position: 'absolute', width: 180, height: 180, borderRadius: 90, borderWidth: 24, borderColor: '#284D41', right: -70, top: -75 },
  heroTitle: { fontSize: 31, lineHeight: 39, color: '#FFFFFF', fontWeight: '600', letterSpacing: -.7, marginTop: 20 },
  heroBody: { color: '#BFD3C8', fontSize: 13, lineHeight: 21, marginTop: 10, marginBottom: 22 },
  heroLabel: { color: '#C4D9C9', fontSize: 10, letterSpacing: 1.5, fontWeight: '600' },
  heroButton: { backgroundColor: colors.lime },
  heroButtonText: { color: colors.ink },
  stats: { flexDirection: 'row', gap: 12, marginBottom: 22 },
  stat: { flex: 1, padding: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18 },
  statValue: { fontSize: 22, fontWeight: '700', color: colors.ink, marginTop: 10, marginBottom: 3 },
  quickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 20 },
  quickAction: { flexGrow: 1, flexBasis: 140, minHeight: 70, paddingHorizontal: 14, paddingVertical: 14, flexDirection: 'row', gap: 10, alignItems: 'center', borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  quickLabel: { fontSize: 12, fontWeight: '600', color: colors.ink },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 16 },
  notice: { flexDirection: 'row', gap: 10, padding: 14, backgroundColor: colors.pale, borderRadius: 14, marginBottom: 16 },
  noticeText: { flex: 1, color: '#52685C', fontSize: 12, lineHeight: 19 },
  error: { padding: 14, backgroundColor: '#FCEDE8', borderRadius: 14, color: '#9E4736', marginBottom: 16, fontSize: 13, lineHeight: 21 },
  filterBar: { flexDirection: 'row', padding: 5, borderRadius: 15, backgroundColor: '#EAF0EC', marginBottom: 16 },
  filter: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 11 },
  filterActive: { backgroundColor: '#FFFFFF' },
  filterText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  sourceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 16 },
  chip: { minHeight: 44, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: '#FFFFFF' },
  chipActive: { backgroundColor: colors.pale, borderColor: '#B6CDBD' },
  messageActions: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderColor: colors.border, marginTop: 16, paddingTop: 4, gap: 4 },
  empty: { paddingVertical: 28, alignItems: 'center', gap: 10 },
  connection: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 15, borderBottomWidth: 1, borderColor: colors.border },
  profile: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 20 },
  avatar: { width: 54, height: 54, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E4EEDD' },
  avatarText: { fontSize: 21, color: colors.ink, fontWeight: '700' },
  quote: { padding: 18, backgroundColor: '#F2F6ED', borderRadius: 16, borderLeftWidth: 3, borderLeftColor: '#93B586', marginVertical: 16 },
  footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, marginTop: 16, marginBottom: 10 },
  footerText: { fontSize: 10, color: colors.muted },
});
